import type { Metadata } from "next";
import { Figtree, Space_Mono, Roboto_Condensed, Antonio } from "next/font/google";
import "./globals.css";

const figtree = Figtree({
    variable: "--font-figtree",
    subsets: ["latin"],
});

const spaceMono = Space_Mono({
    variable: "--font-space-mono",
    subsets: ["latin"],
    weight: ["400", "700"],
});

const antonio = Antonio({
    variable: "--font-antonio",
    subsets: ["latin"],
    weight: ["400", "700"],
});

const robotoCondensed = Roboto_Condensed({
    variable: "--font-roboto-condensed",
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={` ${figtree.variable} ${spaceMono.variable} ${antonio.variable} ${robotoCondensed.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
